version: "3.9"

services:
  mongo:
    image: mongo:4.4
    volumes:
      - ./storage/dbs/mongo:/data/db

  api:
    image: node:16
    depends_on:
      - mongo
    command: bash -c " apt update && apt install -y chromium ffmpeg && npm install && npm start"
    working_dir: /app
    volumes:
      - ./api:/app
      - ./storage:/storage
    ports:
      - ${PORT_API}:4000
    environment:
      MONGO_URI: mongodb://mongo:27017

      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      NFT_STORAGE_KEY: ${NFT_STORAGE_KEY}
