version: "3.9"

services:

  mongo:
    image: mongo:4.4
    ports:
      - ${PORT_MONGODB}:27017

  api:
    image: node:16
    command: bash -c " apt update && apt install -y chromium ffmpeg && npm install && npm run dev"
    working_dir: /app
    volumes:
      - ./api:/app
      - ./storage:/storage
    ports:
      - ${PORT_API}:4000
    environment:
      MONGO_URI: mongodb://mongo:27017
      EVM_RPC: http://rpc:9545

      INFURA_IPFS_ID: ${INFURA_IPFS_ID}
      INFURA_IPFS_SECRET: ${INFURA_IPFS_SECRET}
      NFT_STORAGE_KEY: ${NFT_STORAGE_KEY}

  web:
    image: node:16
    command: bash -c "npm install && npm start"
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - ${PORT_WEB}:3000
    environment:
      WDS_SOCKET_PORT: ${PORT_WEB}

  rpc:
    image: node:14
    command: bash -c "npm install && npx truffle develop"
    working_dir: /app
    volumes:
      - ./rpc:/app
    ports:
      - ${PORT_RPC}:9545
